name: libpg
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  crypto: ^3.0.1
  convert: ^3.0.0
  channel: ^2.0.0
  sasl_scram: ^0.1.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.2
